name: Build/release

on: push

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Go mods
        run: go mod download
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Build cli binary file
        run: CGO_ENABLED=1 GOOS=linux go build -a -ldflags "-linkmode external -extldflags -static" -o releases/linux-keyvault-cli ./cli
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Release assets
        if: ${{ startsWith(matrix.os, 'windows') && startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "release/*.*"
          token: ${{ secrets.GITHUB_TOKEN }}
